### ISSUE TITLE
TypeError: process_response() takes 3 positional arguments but 5 were given

### ISSUE THREAD

**Issue by Jithinqw** [Jithinqw/Camembert#1]
While running the Camerbert example. This error is thrown.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.5/dist-packages/falcon/api.py", line 260, in __call__
    process_response(req, resp, resource, req_succeeded)
TypeError: process_response() takes 3 positional arguments but 5 were given
```

**Comment by Jithinqw** [comment]
This is resolved in the 0.3.8 release
